[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short
markers =
    login: Login test cases
    search: Search test cases
    smoke: Smoke test cases
    regression: Regression test cases
    data_driven: Data-driven test cases
